name: Tests HealthTrack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Instalar Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Instalar ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Correr aplicación en puerto 8081
        run: |
          mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8081" &
          sleep 20

      - name: Instalar SoapUI
        run: |
          wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.7.0/SoapUI-5.7.0-linux-bin.tar.gz
          tar -xzf SoapUI-5.7.0-linux-bin.tar.gz
          sudo mv SoapUI-5.7.0 /opt/soapui
          chmod +x /opt/soapui/bin/testrunner.sh

      - name: Ejecutar pruebas de SoapUI
        run: |
          set +e
          echo "Creando carpeta resultados..."
          mkdir -p tests/SoapUI/resultados/pipeline/

          echo "Verificando archivo XML..."
          if [ -f tests/SoapUI/HealthTrackSoapUI.xml ]; then
            echo "Ejecutando pruebas SoapUI..."
            /opt/soapui/bin/testrunner.sh \
              -r -j \
              tests/SoapUI/HealthTrackSoapUI.xml \
              > tests/SoapUI/resultados/pipeline/log.txt 2>&1
            echo "SoapUI ejecutado con código $? (ver log)"
          else
            echo "Archivo HealthTrackSoapUI.xml no encontrado." > tests/SoapUI/resultados/pipeline/log.txt
          fi
        continue-on-error: true

      - name: Subir reporte SoapUI
        uses: actions/upload-artifact@v4
        with:
          name: log-soapui
          path: tests/SoapUI/resultados/pipeline/log.txt

      - name: Ejecutar pruebas de Selenium y JUnit
        run: mvn test
        continue-on-error: true

      - name: Instalar JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter
          /opt/jmeter/bin/jmeter -v

      - name: Ejecutar pruebas de JMeter
        run: |
          mkdir -p tests/JMeter/resultados/pipeline/
          /opt/jmeter/bin/jmeter \
            -n \
            -t tests/JMeter/HealthTrackTestJMeter.jmx \
            -l tests/JMeter/resultados/pipeline/resultados.jtl \
            -e \
            -o tests/JMeter/resultados/pipeline/html

      - name: Subir reporte JMeter
        uses: actions/upload-artifact@v4
        with:
          name: reporte-jmeter
          path: tests/JMeter/resultados/pipeline/html