name: Tests HealthTrack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Instalar Chrome
        run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - name: Instalar ChromeDriver
        uses: seleniumhq/selenium-actions/setup-chromedriver@v1

      - name: Correr aplicación en puerto 8081
        run: |
          mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8081" &
          sleep 25

      - name: Ejecutar pruebas de Selenium y Junit
        run: mvn test
